[package]
name = "VoxelGame"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.38.0" }
metal = "0.32.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.8"
lazy_static = "1.5.0"
fastnoise-lite = "1.1.1"
